# Generated by Django 5.0.1 on 2024-02-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('posts', '0002_alter_posts_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
