# Generated by Django 5.0.1 on 2024-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profiles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
